# Generated by Django 3.2.13 on 2022-05-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='diescription',
            new_name='description',
        ),
    ]
