# Generated by Django 3.2.13 on 2022-05-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_diescription_work_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='suimage',
            new_name='subimage',
        ),
    ]
