# Generated by Django 3.2.13 on 2022-05-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_software_techical'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techical',
            new_name='Technical',
        ),
    ]
